### ISSUE TITLE
下载模版之后，一片红色

### ISSUE THREAD

**Issue by yanghuizhi** [Hanlin-Dong/hexo-theme-adagio#1]
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
Unhandled rejection TypeError: /Users/yhz/Desktop/pypy/yanghuizhi.gittest/themes/ADAGIO/layout/index.ejs:34
    32| </div>
    33|
 >> 34| <%- partial('_partial/footer') %>
    35| <%- partial('_partial/script') %>
    36| </body>
    37| </html>

/Users/yhz/Desktop/pypy/yanghuizhi.gittest/themes/ADAGIO/layout/_partial/footer.ejs:6
    4|             <div class="col text-center">
    5|                 <div class="bottom-social">
 >> 6|                     <%- partial('_partial/_sidebar/socialmedia') %>
    7|                 </div>
    8|                 <p class="copyright text-muted">
    9|                     Copyright &copy; <%- theme.title %>

/Users/yhz/Desktop/pypy/yanghuizhi.gittest/themes/ADAGIO/layout/_partial/_sidebar/socialmedia.ejs:4
    2|     <div class="col text-center">
    3|         <ul class="list-inline">
 >> 4|             <% theme.media_types.forEach(function (mediatype) { %>
    5|             <li class="list-inline-item">
    6|                 <% if (mediatype == 'github') { %>
    7|                 <a href="https://github.com/<%- theme.github_username %>">

Cannot read property 'forEach' of undefined
    at eval (eval at compile (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:26)
    at returnedFn (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiledSync (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/theme/view.js:119:22)
    at Theme._View.View.View.renderSync (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (eval at compile (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:17)
    at returnedFn (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiledSync (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/theme/view.js:119:22)
    at Theme._View.View.View.renderSync (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (eval at compile (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:41:17)
    at returnedFn (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiled (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/theme/view.js:123:48)
    at Theme._View.View.View.render (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/hexo/index.js:349:21
    at tryCatcher (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/yhz/Desktop/pypy/yanghuizhi.gittest/node_modules/hexo/lib/hexo/router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:474:10)
    at resume_ (_stream_readable.js:953:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by Hanlin-Dong** [comment]
你好，我测试了一下，并没有报错。请再次核对theme文件夹中config的内容。对于`media_types`一项要输入一个array，可能是您没有定义这个array造成的。
